@Host = http://localhost:5059

###

PUT {{Host}}/api/entity
Content-Type: application/json

{
  "id": "cfaa0d3f-7fea-4423-9f69-ebff826e2f89",
  "operationDate": "2019-04-02T13:10:20.0263632+03:00",
  "amount": 23.05
}

###

GET {{Host}}/api/entity/cfaa0d3f-7fea-4423-9f69-ebff826e2f89
Accept: application/json